### ISSUE TITLE
API: Create django rest-framework baseline

### ISSUE THREAD

**Issue by wei-huang-dev** [wei-huang-dev/vue_django_demo#1]
1. Create virtual env 
2. Create Django project
3. Update settings to use django rest  framework
4. Push into this repo and post the link below

**Comment by wei-huang-dev** [comment]
[a23eb13](https://github.com/wei-huang-dev/vue_django_demo/commit/a23eb1327d1a96439f070a244c6f90072c9c5966)

**Comment by GusHenriq** [comment]
c5fb11eca454ce6fae42790396631dccc64bcad2
