### ISSUE TITLE
UI: Test how many entries we can fit on a table while still readable

### ISSUE THREAD

**Issue by GusHenriq** [wei-huang-dev/vue_django_demo#20]
The client would ideally want to see as many columns of data on the screen at once while being able to view the data. For example a months worth of entries and their associated column data. 

Add many more entries to the table. Ideally there will be a horizontal scrollbar at the bottom of the table to scroll through left and right to view different entries. 

So for example in the table now there is just 6/1/22 and 6/2/22. Try putting a month's worth of separate entries to see how it looks. And when they become too much have a scrollbar to navigate through them.

**Comment by nickhoang1** [comment]
All table column entries can be scrolled left and right using the horizontal scrollbar as needed. 
All table row entries can also  be scrolled up and down using the vertical scrollbar as needed.
Also add the fixed date row and field column.
